###Get all users:
GET https://p4-blogs.onrender.com/api/users
###POST user 1
POST https://p4-blogs.onrender.com/api/users
Content-Type: application/json

{
  "username": "123123",
  "name": "Ipsum",
  "password": "password"
}
###
POST https://p4-blogs.onrender.com/api/users
Content-Type: application/json

{
  "username": "lalalala",
  "name": "Lorem",
  "password": "P!assword"
}
###
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "user1",
  "name": "User1",
  "password": "password1"
}
###
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "user2",
  "name": "User2",
  "password": "password2"
}
