###Get all users:
GET https://p4-blogs.onrender.com/api/users
###POST
POST https://p4-blogs.onrender.com/api/users
Content-Type: application/json

{
  "username": "12",
  "name": "Bob",
  "password": "password"
}

POST https://p4-blogs.onrender.com/api/users
Content-Type: application/json

{
  "username": "lalalala",
  "name": "Lorem",
  "password": "P!assword"
}