###Get token:
POST https://p4-blogs.onrender.com/api/login
Content-Type: application/json

{
  "username": "lalalala",
  "name": "Lorem",
  "password": "P!assword"
}
###Use token to post a blog
POST https://p4-blogs.onrender.com/api/login
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImxhbGFsYWxhIiwiaWQiOiI2NDgxZWQ1MjAzZDNmOTllOTUxZDg0ODIiLCJpYXQiOjE2ODYyNDA1OTl9.0JomWfdiAdePhX44O-ZtP-pLi3Pmx-PhFJ_OlSwWjj8

{
  "title": "React patterns",
  "url": "https://reactpatterns.com/",
  "likes": 7
}