###Get token:
POST https://p4-blogs.onrender.com/api/login
Content-Type: application/json

{
  "username": "lalalala",
  "name": "Lorem",
  "password": "P!assword"
}
###Use token to post a blog
POST https://p4-blogs.onrender.com/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImxhbGFsYWxhIiwiaWQiOiI2NDgyM2U0Nzk0NTA4NDhlN2RhMDk4MWUiLCJpYXQiOjE2ODYyNTcyNDksImV4cCI6MTY4NjI2MDg0OX0.23rX1m4LOxAT-ESqhmxAGo52mckno_5V2hiK9VEhHEw

{
  "title": "React patterns",
  "url": "https://reactpatterns.com/",
  "likes": 7
}
###Get blogs (to use to delete a blog below)
GEt https://p4-blogs.onrender.com/api/blogs

###Delete a blog:
DELETE https://p4-blogs.onrender.com/api/blogs/64823e6e9450848e7da09824
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImxhbGFsYWxhIiwiaWQiOiI2NDgyM2U0Nzk0NTA4NDhlN2RhMDk4MWUiLCJpYXQiOjE2ODYyNTcyNDksImV4cCI6MTY4NjI2MDg0OX0.23rX1m4LOxAT-ESqhmxAGo52mckno_5V2hiK9VEhHEw

{
  "title": "React patterns",
  "url": "https://reactpatterns.com/",
  "likes": 7
}