###Get token:
POST https://p4-blogs.onrender.com/api/login
Content-Type: application/json

{
  "username": "lalalala",
  "name": "Lorem",
  "password": "P!assword"
}
###Use token to post a blog
POST https://p4-blogs.onrender.com/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImxhbGFsYWxhIiwiaWQiOiI2NDgxZWQ1MjAzZDNmOTllOTUxZDg0ODIiLCJpYXQiOjE2ODYyNDE0ODYsImV4cCI6MTY4NjI0NTA4Nn0.33C1S_AhU3Y9v5Ssx74jA0qfhbLNkhAMC9pNy8W6DWQ

{
  "title": "React patterns",
  "url": "https://reactpatterns.com/",
  "likes": 7
}