###Test for getting blog
GET https://p4-blogs.onrender.com/api/blogs
###Post blog 1 test:
POST https://p4-blogs.onrender.com/api/blogs
Content-Type: application/json

{
  "title": "React patterns",
  "url": "https://reactpatterns.com/",
  "likes": 7
}
###Post blog 2 test:
POST https://p4-blogs.onrender.com/api/blogs
Content-Type: application/json

{
  "title": "Go To Statement Considered Harmful",
  "url": "http://www.u.arizona.edu/~rubinson/copyright_violations/Go_To_Considered_Harmful.html",
  "likes": 5
}