### Get all persons:
GET https://phonebook-ga8t.onrender.com/api/persons
### Get information:
GET https://phonebook-ga8t.onrender.com/api/info
### Post some info:
POST https://phonebook-ga8t.onrender.com/api/persons
Content-type: application/json

{
    "name": "Testing May 22",
    "number": "22/05/2023"
}
